[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hydromodel"
version = "0.1.0"
description = "1D Saint-Venant hydrodynamic model"
authors = [
    {name = "Mohammed Omer"}
]
dependencies = []
